-- TOTAL REVENUE
create view property_table as 
select fact_bookings.property_id,property_name, category, city, revenue_realized, room_category from fact_bookings join dim_hotels 
on  fact_bookings.property_id = dim_hotels.property_id;
select * from property_table ;
create view Revenue_table as 
select property_id, property_name,category,city,revenue_realized,room_category, room_class
 from property_table join dim_rooms on property_table.room_category= dim_rooms.room_id;
 
 -- TOTAL REVENUE GENERATED BY EACH PROPERTY & ITS CATEGORY
 select  property_name, category, city, sum(revenue_realized) as Total_Revenue from Revenue_table
 group by property_name,category,city order by city desc,Total_Revenue desc;
 
                                     -- Mumbai Performance:
-- Atliq Exotica leads the luxury category, indicating a strong brand presence and customer preference for this property.
-- Atliq Bay shows the least revenue in the luxury category, suggesting potential issues with market penetration, customer satisfaction, or competition.
-- Investigate the factors leading to low performance in the luxury category and develop strategies to enhance its appeal, such as improving marketing efforts, enhancing service quality, or offering promotions.
									 -- Hyderabad Performance:
-- Atliq Bay excels in the luxury category, highlighting a successful strategy or strong market demand in this city.
-- Atliq Palace in the business category has the least revenue, indicating possible challenges in attracting business travelers or competitive disadvantage.
-- Identify the reasons for underperformance in the business category and address them through targeted improvements in amenities, services, or pricing strategies to attract more business travelers.
                                    -- Delhi Performance:
-- Atliq Palace dominates the business category, reflecting a strong position in the market for business accommodations.
-- Atliq Grads records the lowest revenue in the luxury category, which could be due to intense competition, brand perception, or service issues.
-- Assess the competitive landscape and customer expectations in the luxury market to develop initiatives that can improve the property’s attractiveness and revenue.
                                    -- Banglore Performance
-- Atliq Bay: Effective market strategy leading to the highest revenue in the luxury category.
-- Atliq Grand: Possible reasons for the lowest performance in the luxury category could be related to market competition, service quality, or customer awareness.
-- Analyze factors contributing to low performance and develop strategies to enhance market position, such as improving service quality, increasing marketing efforts, or offering competitive pricing.

-- TOTAL BOOKINGS

 create view booking_table as 
select booking_id,fact_bookings.property_id,property_name, category, city, revenue_realized, room_category from fact_bookings join dim_hotels 
on  fact_bookings.property_id = dim_hotels.property_id;
select property_name,category, city , count(booking_id) as Total_Bookings,
SUM(COUNT(booking_id)) OVER(PARTITION BY property_name) AS Total_Bookings_per_Property
from booking_table group by property_name,category,city order by property_name desc, Total_Bookings_per_Property desc;

-- Atilq Palace & Atilq Exotica has highest number of total bookings out of all other properties.
-- Atliq Seasons has the lowest total bookings among all Atliq properties.
-- One of the main reasons for this is that it operates only in one city, Mumbai. This limited geographical presence can significantly impact its market reach and overall bookings.

-- Average_ratings
CREATE VIEW  average_ratings AS
SELECT fact_bookings.property_id, property_name,category,ratings_given FROM fact_bookings 
JOIN dim_hotels ON fact_bookings.property_id=dim_hotels.property_id;

CREATE VIEW avgg_ratings AS 
SELECT 
    property_name, 
    category, 
    AVG(ratings_given) OVER (PARTITION BY category) AS avg_ratings_of_category,
    AVG(ratings_given) OVER (PARTITION BY property_name, category) AS avg_ratings_of_property
FROM 
    average_ratings
ORDER BY 
    avg_ratings_of_category DESC,avg_ratings_of_property DESC ;
SELECT DISTINCT * FROM avgg_ratings;
-- While the business class properties overall tend to have higher ratings than luxury properties, Atliq Blu, a luxury property, surpasses all others, including the top-rated business property, Atliq City. 
-- This suggests that Atliq Blu excels exceptionally in areas that drive high customer satisfaction, setting a benchmark for quality and service that even the best business properties cannot match.

													-- TOTAL CAPACITY

CREATE VIEW property_capacity AS
SELECT property_name, room_category, capacity from fact_aggregated_bookings join
dim_hotels on fact_aggregated_bookings.property_id = dim_hotels.property_id;
CREATE TABLE capacity AS 
SELECT property_name,room_class,capacity from property_capacity join
dim_rooms on property_capacity.room_category = dim_rooms.room_id;
CREATE VIEW capacity_table AS
SELECT  property_name,room_class,sum(capacity) OVER(partition by room_class) as Capacity_per_room_category,
sum(capacity) OVER(partition by property_name) as Capacity_per_property,
sum(capacity) OVER(partition by property_name,room_class) as Capacity_per_property_room
from capacity 
order by Capacity_per_room_category desc,Capacity_per_property desc,  Capacity_per_property_room desc;
select distinct * from capacity_table;

-- Atliq Exotica is the preferred choice for accommodating a larger number of guests due to its highest capacity.
-- Elite stands as a middle ground with a moderate capacity, but it's important to note that  Presidential class rooms have the least capacity, making it less suitable for guests looking for high-capacity, premium accommodation.
-- Atliq Season is the least suitable for large groups or high-capacity needs, as it has the lowest overall capacity. It might be more appropriate for guests looking for a quieter, more exclusive experience with fewer rooms available.


												  -- TOTAL SUCCESSFUL BOOKINGS

CREATE VIEW property AS
SELECT property_name, category, booking_status from fact_bookings join
dim_hotels on dim_hotels.property_id = fact_bookings.property_id;
select * from property;
select property_name,category, count(booking_status) as Total_Successful_bookings
from property where booking_status = "Checked Out" 
group by property_name, category order by Total_Successful_bookings desc; 

-- Atliq City should continue to focus on its business category as it has proven to be the most successful in terms of bookings. 
-- This property can further enhance its services to business travelers to maintain and possibly increase its success rate.
-- Atliq Grands and Atliq Season need strategic interventions to boost their booking success. 
-- This could include targeted marketing campaigns, promotional offers, improving amenities, or re-evaluating their market positioning to better attract potential guests.


                                                    -- OCCUPANCY %
SELECT 
    SUM(Total_Successful_bookings) / (SELECT SUM(capacity) FROM capacity)*100 as Occupany from
    (select property_name,category, count(booking_status) as Total_Successful_bookings
from property where booking_status = "Checked Out" 
group by property_name, category order by Total_Successful_bookings desc) as subquery;

-- The overall occupancy rate of 4.09 indicates room for growth.
-- By leveraging the strengths of Atliq City and addressing the weaknesses in Atliq Grands and Atliq Season, Atliq Hospitality can improve its overall occupancy rate.

                                             -- TOTAL CANCELLED BOOKINGS

CREATE VIEW property AS
SELECT property_name, category, booking_status from fact_bookings join
dim_hotels on dim_hotels.property_id = fact_bookings.property_id;
select * from property;
select property_name,category, count(booking_status) as Total_Cancelled_bookings
from property where booking_status = "Cancelled" 
group by property_name, category order by Total_Cancelled_bookings desc; 

-- Focus on Reducing Cancellations:
-- Investigate Causes: Understand why cancellations are higher. This could include reasons such as pricing, booking flexibility, guest satisfaction, or competitive alternatives.
-- Improve Booking Policies: Consider more flexible cancellation policies, better communication with guests, and enhancements to the booking experience.


                                               -- CANCELLATION RATE
Select sum(total_cancelled_bookings)/ (select sum(booking_count) from ( SELECT COUNT(booking_status) AS booking_count
                                 FROM fact_bookings
                                 GROUP BY property_id
                             )as subqueery ) as cancellation_rate from
                             (select property_name,category, count(booking_status) as total_cancelled_bookings
from property where booking_status = "Cancelled" 
group by property_name, category order by total_cancelled_bookings desc) as cancelled_subquery;

-- The overall cancellation rate of 25.30% at Atliq Hospitality indicates that approximately one in four bookings are being canceled. 
-- This is a significant proportion and suggests that the company may need to investigate the underlying causes.
-- Booking Policies, Customer Behavior Analysis, Service and Quality Improvements, Competitor Comparison, Marketing and Communication etc.

											-- CANCELLATION RATE OF EACH PROPERTY
WITH TotalBookings AS (SELECT property_name,COUNT(booking_status) AS total_bookings
    FROM property
    GROUP BY property_name)
SELECT p.property_name, p.category, COUNT(p.booking_status) / tb.total_bookings AS Cancellation_rate
FROM property p
JOIN TotalBookings tb ON p.property_name = tb.property_name
WHERE p.booking_status = 'Cancelled'
GROUP BY p.property_name, p.category
ORDER BY Cancellation_rate DESC;
